### ISSUE TITLE
Follow the python version of pulsar admin 

### ISSUE THREAD

**Issue by jackray2009** [protocol-laboratory/pulsar-admin-python#6]
# pulsar-admin-python issue

# 1、Version

Notice: The python version used in the current project is 3.X

# 2、Interface impl

- Urgent(Guaranteed availability)
    -  tenant
    -  namespace
    -  topic
    -  sink
    -  source
    -  package
 - It's not urgent, but it's important
   - broker
   - cluster
   - function
   - schema
   - resource
   - transaction
   - auth for iam
  
# 3、DFX/Performance testing

# 4、packgae for whl

- win
- linux
- mac

**Comment by hezhangjian** [comment]
Thank you for raising your request. We will work on it gradually. If you are interested, you can also participate and contribute to the code.
